import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import { getGenres } from "@/utils/api";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type GenreType = { genres: Genre[] };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const genresData = (await getGenres()) as GenreType;

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen grid grid-cols-1 md:grid-cols-[1fr 3fr] scroll-smooth">
          <Navbar />
          <Sidebar genres={genresData?.genres ?? []} />
          {children}
        </div>
      </body>
    </html>
  );
}
